- name: demo on nginx
  hosts: frontend
  become: true
  tasks:
  - name: install nginx
    package:
      name: nginx
      state: present
  - name: start service
    service:
      name: nginx
      state: started
      enabled: yes