- name: Demo on file
  hosts: local
  connection: local
  vars_files:
   - course.yaml
   tasks:
     - name: print data
      debug:
       msg: "dETAILS ARE {{ COURSE }} {{ TRAINER }} {{ DURATION }}"