---
- name: Demo on file
  hosts: local
  connection: local

  vars_files:
    - course.yaml

  tasks:
    - name: Print data
      debug:
        msg: "DETAILS ARE {{ COURSE }} {{ TRAINER }} {{ DURATION }}"